#!/usr/bin/env python3
"""params.json -> build/params_gen.h (enum P_<KEY>, per-param name/type) and build/pluginlist-entry.xml."""
#    KEY ARRAYS: a "grid" param (the search box's key grid) also emits
#      <KEY>_N / <KEY>_CHARS[]  -- one character per option, the LAST entry a '\0'-marked
#      dead cell (see params.json's comment on query_key).
#    popup_of: a "flag" param names its popup's param; the wrapper keeps the flag itself
#      (never sent to the core, never saved) and clears it when a grid key is picked.
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
spec = json.load(open(os.path.join(ROOT, "params.json")))
out = os.path.join(ROOT, "build")
os.makedirs(out, exist_ok=True)
types = {"stepper": "T_STEPPER", "trigger": "T_TRIGGER", "float": "T_FLOAT", "readout": "T_READOUT",
         "slot": "T_SLOT", "grid": "T_GRID", "flag": "T_FLAG"}
params = spec["params"]
keys = [p["key"] for p in params]
lines = ["/* generated by gen_params.py from params.json - do not edit */", "#pragma once",
         "enum { T_STEPPER, T_TRIGGER, T_FLOAT, T_READOUT, T_SLOT, T_GRID, T_FLAG };",
         "typedef struct { const char *key, *name; int type; float min, max, def; int popup_of; } param_t;", "enum {"]
lines += ["    P_%s," % p["key"].upper() for p in params]
lines += ["    NPARAMS", "};", "static const param_t PARAMS[NPARAMS] = {"]
for p in params:
    lo, hi = p.get("min", 0), p.get("max", 1)
    d = p.get("default", lo)
    norm = (d - lo) / (hi - lo) if hi > lo else 0
    lines.append('    {"%s", "%s", %s, %rf, %rf, %rf, %d},' % (
        p["key"], p["name"], types[p["type"]], float(lo), float(hi), float(norm),
        keys.index(p["popup_of"]) if p.get("popup_of") else -1))
lines += ["};"]
def c_char(ch):
    """One character as a C char literal (the grid's charset is letters, digits, space and
    punctuation, so only the quote and a backslash need escaping)."""
    if ch == "\\":
        return "'\\\\'"
    if ch == "'":
        return "'\\''"
    return "'%s'" % ch


for p in params:
    if p["type"] != "grid":
        continue
    key = p["key"].upper()
    chars = p["chars"]
    # One drawn option per label == one character per key, spacer cell included (the skin draws
    # len(options) cells; chars has one fewer because the spacer types nothing).
    assert len(p["options"]) == len(chars) + 1, "%s: %d option labels but %d chars" % (
        p["key"], len(p["options"]), len(chars))
    literals = [c_char(c) for c in chars]
    literals.append("0")   # the dead cell: the host never reports a tap on it (see params.json)
    lines.append("")
    lines.append("/* %s: %s */" % (p["key"], p["name"]))
    lines.append("#define %s_N %d" % (key, len(p["options"])))
    lines.append("static const char %s_CHARS[%s_N] = { %s };" % (key, key, ", ".join(literals)))
lines += ['#define PLUG_NAME "%s"' % spec["name"], '#define PLUG_VENDOR "%s"' % spec["vendor"],
          "#define PLUG_UID 0x%08x /* '%s' */" % (int.from_bytes(spec["uid"].encode(), "big"), spec["uid"]),
          "#define PLUG_VERSION %d" % spec["version"]]
open(os.path.join(out, "params_gen.h"), "w").write("\n".join(lines) + "\n")
so = spec["name"].lower().replace(" ", "")
open(os.path.join(out, "pluginlist-entry.xml"), "w").write(
    '<PLUGIN name="{n}" descriptiveName="{n}" format="VST" category="Synth" manufacturer="{v}" version="1.0" '
    'file="/sdcard/vst/{so}.so" uid="{u:x}" isInstrument="1" fileTime="0" infoUpdateTime="0" numInputs="0" '
    'numOutputs="2" isShell="0"/>\n'.format(n=spec["name"], v=spec["vendor"], so=so,
                                           u=int.from_bytes(spec["uid"].encode(), "big")))
print("params_gen.h: %d params" % len(spec["params"]))
